from collections import Counter, defaultdict
import ast
import os
from pathlib import Path
from pprint import pformat
from typing import cast

import pandas as pd
from loguru import logger

from todoist.constants import EventExtraField
from todoist.database.base import Database
from todoist.env import EnvVar
from todoist.types import SUPPORTED_EVENT_TYPES, Event, events_to_dataframe
from todoist.utils import Cache, LocalStorageError

ADJUSTMENTS_VARIABLE_NAME = 'link_adjustements'
DEFAULT_ADJUSTMENTS_FILENAME = 'archived_root_projects.py'


def resolve_personal_dir() -> Path:
    override = os.getenv(str(EnvVar.PERSONAL_DIR))
    if override:
        return Path(override).expanduser().resolve()
    return (Path.cwd() / "personal").resolve()


def normalize_adjustment_filename(filename: str) -> str:
    candidate = filename.strip()
    if not candidate:
        raise ValueError("Adjustment file name is required")
    if Path(candidate).name != candidate:
        raise ValueError("Adjustment file name must not include path separators")
    if Path(candidate).suffix != ".py":
        raise ValueError("Adjustment file name must end with .py")
    if candidate.startswith(".") or candidate in {".", ".."}:
        raise ValueError("Adjustment file name must be a simple filename")
    return candidate


def render_adjustments_file_content(
    mappings: dict[str, str], archived_parents: list[str] | None = None
) -> str:
    archived_parents = archived_parents or []
    sorted_mappings = dict(sorted(mappings.items(), key=lambda item: item[0]))
    sorted_archived_parents = sorted(set(archived_parents))
    content = [
        "# Adjustments for archived root projects",
        "# This file was generated by the web dashboard admin UI",
        "",
        f"{ADJUSTMENTS_VARIABLE_NAME} = {pformat(sorted_mappings, sort_dicts=True)}",
        "",
        f"archived_parent_projects = {pformat(sorted_archived_parents)}",
        "",
    ]
    return "\n".join(content)


def _load_adjustments_literal_file(path: Path) -> tuple[dict[str, str], list[str]]:
    try:
        raw_text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValueError(f"Unable to read adjustment file: {path.name}") from exc

    try:
        module = ast.parse(raw_text, filename=str(path))
    except SyntaxError as exc:
        raise ValueError(f"Invalid adjustment file syntax: {path.name}") from exc

    mapping: dict[str, str] | None = None
    archived_parents: list[str] | None = None
    for node in module.body:
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            continue
        if not isinstance(node, ast.Assign):
            raise ValueError(
                "Adjustment files may only contain literal assignments and comments"
            )
        if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
            raise ValueError("Unsupported adjustment assignment")
        target_name = node.targets[0].id
        try:
            value = ast.literal_eval(node.value)
        except (ValueError, SyntaxError) as exc:
            raise ValueError(f"Adjustment file contains non-literal values: {path.name}") from exc
        if target_name == ADJUSTMENTS_VARIABLE_NAME:
            if not isinstance(value, dict) or not all(
                isinstance(key, str) and isinstance(val, str) for key, val in value.items()
            ):
                raise TypeError(
                    f'"{ADJUSTMENTS_VARIABLE_NAME}" in {path.name} must be a string-to-string dict'
                )
            mapping = dict(value)
        elif target_name == "archived_parent_projects":
            if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
                raise TypeError(
                    f'"archived_parent_projects" in {path.name} must be a list of strings'
                )
            archived_parents = list(value)

    return mapping or {}, archived_parents or []


def load_adjustments_file(filename: str | Path) -> tuple[dict[str, str], list[str]]:
    path = Path(filename)
    if path.suffix != ".py":
        raise ValueError("Adjustment files must use the .py extension")
    return _load_adjustments_literal_file(path)


def extract_name(event: Event) -> str | None:
    """
    Extracts the event name from the event's extra data.
    """
    extra = event.event_entry.extra_data
    if EventExtraField.CONTENT in extra:
        return extra[EventExtraField.CONTENT]
    if EventExtraField.NAME in extra:
        return extra[EventExtraField.NAME]
    return None


def get_adjusting_mapping(specific_file: str | None = None) -> dict[str, str]:
    """
    Loads mapping adjustments from Python scripts in the 'personal' directory.

    Args:
        specific_file: Optional specific filename to load. If None, loads all Python files.
                      If provided, only loads from that specific file.
    """
    personal_dir = resolve_personal_dir()

    if not personal_dir.exists():
        logger.warning(f'Personal directory {personal_dir} does not exist. No adjustments will be made.')
        personal_dir.mkdir(parents=True, exist_ok=True)
        (personal_dir / DEFAULT_ADJUSTMENTS_FILENAME).write_text(
            render_adjustments_file_content({}, []),
            encoding="utf-8",
        )
        logger.info(f'Created empty adjustments file in {personal_dir}')
        return {}

    # Determine which files to load.
    if specific_file:
        safe_specific = normalize_adjustment_filename(specific_file)
        scripts = [safe_specific] if (personal_dir / safe_specific).exists() else []
        logger.info(f'Loading specific mapping file: {safe_specific}')
    else:
        scripts = [
            path.name
            for path in sorted(personal_dir.iterdir())
            if path.is_file() and path.suffix == ".py"
        ]
        logger.info(f'Found {len(scripts)} scripts in personal directory')

    final_mapping: dict[str, str] = {}
    for script in scripts:
        script_path = personal_dir / normalize_adjustment_filename(script)
        link_adjustements, _archived_parent_projects = load_adjustments_file(script_path)
        final_mapping.update(link_adjustements)

    return final_mapping


def _find_duplicate_project_names(
    mapping_project_id_to_name: dict[str, str]
) -> dict[str, list[str]]:
    grouped_ids: dict[str, list[str]] = defaultdict(list)
    for project_id, project_name in mapping_project_id_to_name.items():
        grouped_ids[project_name].append(project_id)
    return {
        project_name: sorted(project_ids)
        for project_name, project_ids in grouped_ids.items()
        if len(project_ids) > 1
    }


def _resolve_root_project_name_to_id(
    _dbio: Database,
) -> tuple[dict[str, str], dict[str, list[str]], set[str], set[str]]:
    active_roots = [
        project
        for project in _dbio.fetch_projects(include_tasks=False)
        if project.project_entry.parent_id is None
    ]
    archived_roots = [
        project
        for project in _dbio.fetch_archived_projects()
        if project.project_entry.parent_id is None
    ]

    active_by_name: dict[str, list[str]] = defaultdict(list)
    archived_by_name: dict[str, list[str]] = defaultdict(list)
    for project in active_roots:
        active_by_name[project.project_entry.name].append(project.id)
    for project in archived_roots:
        archived_by_name[project.project_entry.name].append(project.id)

    resolved: dict[str, str] = {}
    ambiguous: dict[str, list[str]] = {}
    all_root_names = set(active_by_name) | set(archived_by_name)
    for project_name in sorted(all_root_names):
        active_ids = sorted(active_by_name.get(project_name, []))
        archived_ids = sorted(archived_by_name.get(project_name, []))
        if len(active_ids) == 1:
            resolved[project_name] = active_ids[0]
            continue
        if len(active_ids) > 1:
            ambiguous[project_name] = active_ids + archived_ids
            continue
        if len(archived_ids) == 1:
            resolved[project_name] = archived_ids[0]
            continue
        if len(archived_ids) > 1:
            ambiguous[project_name] = archived_ids

    return resolved, ambiguous, set(active_by_name), set(archived_by_name)


def _summarize_counter(counter: Counter[str], *, limit: int = 10) -> str:
    if not counter:
        return '(none)'
    parts = [f'{name}={count}' for name, count in counter.most_common(limit)]
    if len(counter) > limit:
        parts.append(f'... (+{len(counter) - limit} more)')
    return ', '.join(parts)


def load_activity_data(_dbio: Database) -> pd.DataFrame:
    """
    Loads and processes the activity data from joblib file and database mappings.
    """
    activity_filename = 'activity.joblib'
    # activity_db: set[Event] = load(activity_filename) if exists(activity_filename) else set()
    try:
        activity_db: set[Event] = Cache().activity.load()
    except LocalStorageError as exc:
        logger.warning("Failed to load activity cache; using empty set: {}", exc)
        activity_db = set()

    # Filter supported events and check for events with missing titles
    supported_events = list(filter(lambda ev: ev.event_entry.event_type in SUPPORTED_EVENT_TYPES, activity_db))
    no_title_events = sorted(filter(lambda ev: extract_name(ev) is None, supported_events),
                             key=lambda ev: ev.event_entry.event_date)
    if no_title_events:
        logger.warning(f'Found {len(no_title_events)} events without title.')

    logger.info(f'Loaded {len(activity_db)} events from {activity_filename}.')
    mapping_project_id_to_root = _dbio.fetch_mapping_project_id_to_root()
    logger.success(f'Loaded project id to root mapping ({len(mapping_project_id_to_root)} entries)')
    mapping_project_id_to_name = _dbio.fetch_mapping_project_id_to_name()
    logger.success(f'Loaded project id to name mapping ({len(mapping_project_id_to_name)} entries)')
    duplicate_project_names = _find_duplicate_project_names(mapping_project_id_to_name)
    if duplicate_project_names:
        logger.warning(
            'Detected {} duplicate project names in id->name mapping: {}',
            len(duplicate_project_names),
            _summarize_counter(Counter({
                project_name: len(project_ids)
                for project_name, project_ids in duplicate_project_names.items()
            })),
        )
    root_name_to_id, ambiguous_root_names, active_root_names, archived_root_names = (
        _resolve_root_project_name_to_id(_dbio)
    )
    logger.success(
        'Resolved root name to id mapping (resolved={}, active_roots={}, archived_roots={}, ambiguous_roots={})',
        len(root_name_to_id),
        len(active_root_names),
        len(archived_root_names),
        len(ambiguous_root_names),
    )
    if ambiguous_root_names:
        logger.warning(
            'Ambiguous root project names detected: {}',
            _summarize_counter(Counter({
                project_name: len(project_ids)
                for project_name, project_ids in ambiguous_root_names.items()
            })),
        )
    logger.info('Creating dataframe from events...')

    df = events_to_dataframe(activity_db,
                             project_id_to_name=mapping_project_id_to_name,
                             project_id_to_root=mapping_project_id_to_root)

    original_root_id = df['root_project_id'].copy()
    original_root_name = df['root_project_name'].astype(str).copy()
    link_mapping = get_adjusting_mapping()
    effective_link_mapping = {
        source_name: target_name
        for source_name, target_name in link_mapping.items()
        if source_name != target_name
    }
    logger.info(
        'Loaded {} link adjustments ({} effective renames, {} self-maps)',
        len(link_mapping),
        len(effective_link_mapping),
        len(link_mapping) - len(effective_link_mapping),
    )
    logger.info('Adjusting root project names...')
    adjustment_sources = cast(
        pd.Series,
        original_root_name[original_root_name.isin(link_mapping)],
    )
    effective_adjustment_sources = cast(
        pd.Series,
        original_root_name[original_root_name.isin(effective_link_mapping)],
    )
    logger.info(
        'Adjustment rules matched {} rows across {} source root names',
        len(adjustment_sources),
        adjustment_sources.nunique(),
    )
    if len(adjustment_sources):
        logger.debug(
            'Adjustment source row counts: {}',
            _summarize_counter(Counter(adjustment_sources.to_list())),
        )
    logger.info(
        'Effective rename rules matched {} rows across {} source root names',
        len(effective_adjustment_sources),
        effective_adjustment_sources.nunique(),
    )
    if len(effective_adjustment_sources):
        logger.debug(
            'Effective rename source row counts: {}',
            _summarize_counter(Counter(effective_adjustment_sources.to_list())),
        )
    unused_effective_sources = sorted(
        set(effective_link_mapping) - set(effective_adjustment_sources.astype(str).unique())
    )
    if unused_effective_sources:
        logger.debug(
            'Configured effective rename sources not present in current activity data: {}',
            _summarize_counter(Counter({source_name: 1 for source_name in unused_effective_sources})),
        )

    # Adjust project names and map back to root ids.
    df['root_project_name'] = original_root_name.map(
        lambda name: link_mapping.get(name, name)
    )
    mapped_ids = cast(
        pd.Series,
        df['root_project_name'].map(lambda name: root_name_to_id.get(str(name))),
    )
    df['root_project_id'] = mapped_ids.fillna(original_root_id)
    changed_name_mask = original_root_name != df['root_project_name']
    changed_id_mask = original_root_id != df['root_project_id']

    if changed_name_mask.any():
        logger.debug(
            'Adjustment target row counts: {}',
            _summarize_counter(Counter(df.loc[changed_name_mask, 'root_project_name'].astype(str).to_list())),
        )

    ambiguous_targets = sorted(
        set(df.loc[changed_name_mask, 'root_project_name'].astype(str)) & set(ambiguous_root_names)
    )
    if ambiguous_targets:
        logger.warning(
            'Adjustment targets with ambiguous root ids kept their original ids: {}',
            ', '.join(ambiguous_targets[:10]),
        )

    missing_names = sorted(set(df.loc[changed_name_mask & mapped_ids.isna(), 'root_project_name'].astype(str)))
    if missing_names:
        logger.warning(
            'Missing root project ids for {} adjusted target names: {}',
            len(missing_names),
            ', '.join(missing_names[:10]),
        )

    diff_count = int(changed_id_mask.sum())
    total = len(df)
    ratio = (diff_count / total * 100) if total else 0.0
    logger.info(f'Changed {diff_count} root project ids out of {total} ({ratio:.2f}%)')

    known_root_names = set(root_name_to_id) | set(ambiguous_root_names)
    unresolved_original_roots = sorted(
        {
            root_name
            for root_name in original_root_name.unique()
            if root_name not in known_root_names and root_name not in link_mapping
        }
    )
    if unresolved_original_roots:
        logger.warning(
            'Observed {} root names that are neither current roots nor adjustment sources: {}',
            len(unresolved_original_roots),
            ', '.join(unresolved_original_roots[:10]),
        )
    else:
        logger.debug('All observed root names are current roots or explicitly adjusted.')

    df['date'] = pd.to_datetime(df['date'])
    df.sort_values('date', inplace=True)
    # df.set_index('date', inplace=True)
    df['id'] = df['id'].astype(str)
    df['root_project_id'] = df['root_project_id'].astype(str)

    return df
