from enum import StrEnum


class EnvVar(StrEnum):
    CACHE_DIR = "TODOIST_CACHE_DIR"
    CONFIG_DIR = "TODOIST_CONFIG_DIR"
    DATA_DIR = "TODOIST_DATA_DIR"
    LOGS_DIR = "TODOIST_LOGS_DIR"
    PERSONAL_DIR = "TODOIST_PERSONAL_DIR"

    API_HOST = "TODOIST_API_HOST"
    API_PORT = "TODOIST_API_PORT"
    FRONTEND_HOST = "TODOIST_FRONTEND_HOST"
    FRONTEND_PORT = "TODOIST_FRONTEND_PORT"

    DASHBOARD_DEMO = "TODOIST_DASHBOARD_DEMO"
    MAX_CONCURRENT_REQUESTS = "TODOIST_MAX_CONCURRENT_REQUESTS"

    AGENT_CACHE_PATH = "TODOIST_AGENT_CACHE_PATH"
    AGENT_INSTRUCTIONS_DIR = "TODOIST_AGENT_INSTRUCTIONS_DIR"
    AGENT_MAX_TOOL_LOOPS = "TODOIST_AGENT_MAX_TOOL_LOOPS"
    AGENT_MODEL_ID = "TODOIST_AGENT_MODEL_ID"
    AGENT_DEVICE = "TODOIST_AGENT_DEVICE"
    AGENT_DTYPE = "TODOIST_AGENT_DTYPE"
    AGENT_TEMPERATURE = "TODOIST_AGENT_TEMPERATURE"
    AGENT_TOP_P = "TODOIST_AGENT_TOP_P"
    AGENT_MAX_NEW_TOKENS = "TODOIST_AGENT_MAX_NEW_TOKENS"

    TELEMETRY_ENDPOINT = "TODOIST_TELEMETRY_ENDPOINT"
    TELEMETRY_DEBUG = "TODOIST_TELEMETRY_DEBUG"

    EXPECT_DASHBOARD = "TODOIST_EXPECT_DASHBOARD"
    MSI_PATH = "TODOIST_MSI_PATH"
    PKG_PATH = "TODOIST_PKG_PATH"
    BREW_FORMULA = "TODOIST_BREW_FORMULA"
    BREW_TARBALL = "TODOIST_BREW_TARBALL"

    VERSION = "TODOIST_VERSION"
