plugins {
    id "com.android.application"
}

def releaseKeystorePath = System.getenv("ANDROID_KEYSTORE_PATH")
def releaseKeystorePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
def releaseKeyAlias = System.getenv("ANDROID_KEY_ALIAS")
def releaseKeyPassword = System.getenv("ANDROID_KEY_PASSWORD")
def hasReleaseSigning = releaseKeystorePath && releaseKeystorePassword && releaseKeyAlias && releaseKeyPassword

android {
    namespace "dev.mtyrolski.todoistassistant"
    compileSdk 33

    defaultConfig {
        applicationId "dev.mtyrolski.todoistassistant"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "0.3.4"
    }

    signingConfigs {
        if (hasReleaseSigning) {
            release {
                storeFile file(releaseKeystorePath)
                storePassword releaseKeystorePassword
                keyAlias releaseKeyAlias
                keyPassword releaseKeyPassword
            }
        }
    }

    buildTypes {
        staging {
            initWith release
            signingConfig signingConfigs.debug
            matchingFallbacks = ["release"]
        }

        release {
            if (hasReleaseSigning) {
                signingConfig signingConfigs.release
            }
        }
    }
}
